name: Release to Pypi

on:
  release:
    types: [ published ]

jobs:
  release:
    if: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    container: ghcr.io/opencyphal/toxic:tx22.4.3
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: version-check
      # Fails the release if the release-tag doesn't match the Nunavut version at that tag.
      run: |
        $(python3 ./src/nunavut/_version.py -v --fail-on-mismatch --tag=${{ github.ref }})
    - name: lint
      run: tox -e lint
    - name: test-nnvg
      run: tox -e py311-nnvg
    - name: test-doctest
      run: tox -e py311-doctest,py311-rstdoctest
    - name: test-pytest
      run: tox -e py311-test
    - name: package
      run: tox -e package
    - name: upload
      run: |
        pip3 install twine
        twine upload -u __token__ -p ${{ secrets.PYPI_PASSWORD }} .tox/package/dist/*
